# Generated by Django 4.1.7 on 2023-03-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('category_l1', models.CharField(max_length=255)),
                ('category_l2', models.CharField(max_length=255)),
                ('upc', models.CharField(max_length=255)),
                ('parent_code', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products_table',
            },
        ),
    ]
