# Generated by Django 4.1.7 on 2023-03-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
